/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.74
 * Generated at: 2023-06-02 02:00:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/../include/footer.jsp", Long.valueOf(1685584184702L));
    _jspx_dependants.put("jar:file:/C:/Users/ChoiYJ/Documents/MiddleProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/JSPSubway/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/../include/header.jsp", Long.valueOf(1685611037171L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1683770202906L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<title>Home</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>2호선 알리미</title>\r\n");
      out.write("	\r\n");
      out.write("	<!-- css 연결 -->\r\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/setting.css\" rel=\"stylesheet\">\r\n");
      out.write("	\r\n");
      out.write("	<!-- bootstrap 5.3.2 -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" \r\n");
      out.write("    	rel=\"stylesheet\" integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\" crossorigin=\"anonymous\">\r\n");
      out.write("	\r\n");
      out.write("	<!-- 파비콘 -->\r\n");
      out.write("	<link rel=\"icon\" href=\"#\">\r\n");
      out.write("	\r\n");
      out.write("	<!-- 아이콘 사이트 fontawesome css: https://fontawesome.com -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<!-- header -->\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/Seoul_Metro_Line_2.svg\" height=\"50px\" width=\"50px\" /> <a class=\"navbar-brand name\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">&nbsp \r\n");
      out.write("            2<span class=\"go\">호선</span></a> \r\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("                <ul class=\"navbar-nav ms-auto mb-2 mb-lg-0\">\r\n");
      out.write("                    <li class=\"nav-item\"> <a class=\"nav-link active\" aria-current=\"page\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\"><span class=\"home\">Home</span></a> </li>\r\n");
      out.write("                    <li class=\"nav-item\"> <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/login\">로그인</a> </li>\r\n");
      out.write("                    <li class=\"nav-item\"> <a class=\"nav-link\" href=\"#\">로그아웃</a> </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <div class=\"btn btn-dark\">회원가입</div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"home\">\r\n");
      out.write("		<br>\r\n");
      out.write("		<h1>\r\n");
      out.write("			Hello world! <br>\r\n");
      out.write("			임시 HOME  <br>\r\n");
      out.write("			헤더의 로고를 클릭하면 Home으로 돌아옵니다.  <br>\r\n");
      out.write("		</h1>\r\n");
      out.write("		<br>\r\n");
      out.write("		<hr>\r\n");
      out.write("		\r\n");
      out.write("		회원가입 : \r\n");
      out.write("		<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/userJoin\">\r\n");
      out.write("			<button type=\"button\"> userJoin </button>\r\n");
      out.write("		</a> <br>\r\n");
      out.write("		로그인 : \r\n");
      out.write("		<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/userLogin\">\r\n");
      out.write("			<button type=\"button\"> login </button>\r\n");
      out.write("		</a> <br>\r\n");
      out.write("		<hr>\r\n");
      out.write("		상세보기 페이지 : \r\n");
      out.write("		<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/station/detail\">\r\n");
      out.write("			<button type=\"button\"> detail </button>\r\n");
      out.write("		</a> <br>\r\n");
      out.write("		메인 페이지(진짜 홈) : \r\n");
      out.write("		<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/station/main\">\r\n");
      out.write("			<button type=\"button\"> Main </button>\r\n");
      out.write("		</a> \r\n");
      out.write("	</div>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>2호선 알리미</title>\r\n");
      out.write("	\r\n");
      out.write("	<!-- css 연결 -->\r\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/setting.css\" rel=\"stylesheet\">\r\n");
      out.write("	\r\n");
      out.write("	<!-- 파비콘 -->\r\n");
      out.write("	<link rel=\"icon\" href=\"#\">\r\n");
      out.write("	\r\n");
      out.write("	<!-- 아이콘 사이트 fontawesome css: https://fontawesome.com -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("    \r\n");
      out.write("    <style>\r\n");
      out.write("    footer {\r\n");
      out.write("        background-color: #ECEFF1;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    footer hr {\r\n");
      out.write("        width: 60px;\r\n");
      out.write("        background-color: #00A84D;\r\n");
      out.write("        height: 2px\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    footer .container h6:hover {\r\n");
      out.write("        color: #00A84D;\r\n");
      out.write("    }\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- footer -->\r\n");
      out.write("\r\n");
      out.write("<footer class=\"text-center text-lg-start text-dark fixed-bottom\">\r\n");
      out.write("  \r\n");
      out.write("    <!-- Section: Links  -->\r\n");
      out.write("    <section class=\"\">\r\n");
      out.write("      <div class=\"container text-lg-start mt-6 justify-content-between\">\r\n");
      out.write("        <!-- Grid row -->\r\n");
      out.write("        <div class=\"row mt-4\">\r\n");
      out.write("          <!-- Grid column -->\r\n");
      out.write("          <div class=\"col-3 text-center mx-auto mb-0\">\r\n");
      out.write("            <!-- Content -->\r\n");
      out.write("            <h6 class=\"text-uppercase fw-bold\">###</h6>\r\n");
      out.write("            <hr class=\"mb-4 mt-0 d-inline-block mx-auto\">\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- Grid column -->\r\n");
      out.write("\r\n");
      out.write("          <!-- Grid column -->\r\n");
      out.write("          <div class=\"col-3 text-center mx-auto mb-0\">\r\n");
      out.write("            <!-- Links -->\r\n");
      out.write("            <h6 class=\"text-uppercase fw-bold\">###</h6>\r\n");
      out.write("            <hr class=\"mb-4 mt-0 d-inline-block mx-auto\">\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- Grid column -->\r\n");
      out.write("\r\n");
      out.write("          <!-- Grid column -->\r\n");
      out.write("          <div class=\"col-3 text-center mx-auto mb-0\">\r\n");
      out.write("            <!-- Links -->\r\n");
      out.write("            <h6 class=\"text-uppercase fw-bold\">###</h6>\r\n");
      out.write("            <hr class=\"mb-4 mt-0 d-inline-block mx-auto\">\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- Grid column -->\r\n");
      out.write("\r\n");
      out.write("          <!-- Grid column -->\r\n");
      out.write("          <div class=\"col-3 text-center mx-auto mb-md-0 mb-0\">\r\n");
      out.write("            <!-- Links -->\r\n");
      out.write("            <h6 class=\"text-uppercase fw-bold\">게시판</h6>\r\n");
      out.write("            <hr class=\"mb-4 mt-0 d-inline-block mx-auto\"/>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- Grid column -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Grid row -->\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Section: Links  -->\r\n");
      out.write("\r\n");
      out.write("  </footer>\r\n");
      out.write("  <!-- Footer -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
